language: java
jdk:
  - openjdk14

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту если сборка упала
notifications:
  email:
    recipients:
      -235illino@gmail.com
    on_success: never # default: change
    on_failure: never # default: always
env:
  global:
    - CODECOV_TOKEN="64cdcdb7-9ec1-483f-bd06-b5c049502cbd"